# Generated by Django 3.2.9 on 2021-12-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО сотрудника')),
                ('telephone', models.CharField(db_index=True, max_length=15, verbose_name='Телефон')),
                ('position', models.CharField(db_index=True, max_length=100, verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pictures', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(db_index=True, max_length=250, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('placement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pictures.placement')),
                ('phone', models.CharField(max_length=12)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.gallery', verbose_name='Галерея')),
            ],
            bases=('pictures.placement',),
        ),
        migrations.CreateModel(
            name='Expo',
            fields=[
                ('placement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pictures.placement')),
                ('opening_time', models.DateField(verbose_name='Дата открытия')),
                ('closing_time', models.DateField(verbose_name='Дата закрытия')),
            ],
            bases=('pictures.placement',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('cost', models.FloatField(verbose_name='Цена')),
                ('year', models.IntegerField(default=1, verbose_name='год')),
                ('status', models.IntegerField(choices=[(1, 'New')], default=1, verbose_name='Статус')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.gallery', verbose_name='Галерея')),
                ('placement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pictures.placement', verbose_name='Место')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, max_length=100, verbose_name='Дата')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pictures.employee', verbose_name='Сотрудник')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.picture', verbose_name='Картина')),
                ('placement_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_from', to='pictures.placement', verbose_name='Откуда')),
                ('placement_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_to', to='pictures.placement', verbose_name='Куда')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pictures.country', verbose_name='Страна')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pictures.department', verbose_name='Отдел'),
        ),
    ]
