# Generated by Django 3.2.9 on 2021-12-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_picture_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pictures.genre', verbose_name='Жанр'),
        ),
    ]
